### ISSUE TITLE
Feature request: Descriptive document title elements 

### ISSUE THREAD

**Issue by timng-bcgov** [bcgov/developer-portal#169]
## Overview

The `<title>` element on DevHub pages only display the root folder rather than the contents of the page. This makes it difficult to infer the page's purpose from the browser's title bar, page tab, or shared links. 

For example, all content in `/aps-infra-platform-docs/` has the same title: `API Program Services | B.C. government DevHub`.

## Rationale

The page title is relevant to SEO and accessibility since assistive technology users cannot understand the page contents from the title alone. Page titles should be unique to each page of a website and surface the primary purpose of every page that users navigate to in DevHub.

## Expected outcome

The primary purpose of the page is clearly indicated by the page title. The `<title>` elements contain page titles as defined in documentation pages. 

For example, `/aps-infra-platform-docs/tutorials/quick-start/` displays `Quick Start | API Program Services | B.C. government DevHub` where `Quick Start` is the h1 heading of the page.

**Comment by rustyjux** [comment]
+1 on this issue!

**Comment by MonicaG** [comment]
This is an issue with the backstage framework. There is an issue, backstage/backstage#15289, for it which I've commented on.

**Comment by MonicaG** [comment]
Looks like this has been resolved in backstage/backstage#28876
